swagger: "2.0"
info:
  version: "0.0.1"
  title: StreetArt App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
- application/json
- application/javascript
- text/html
x-a127-config: {}
x-a127-services: {}
paths:
  /streetart:
    # binds a127 app logic to a route
    x-swagger-router-controller: street_art
    x-a127-apply: {}
    get:
      description: Returns streetart photos from Flickr for specified city 
      # used as the method name of the controller
      operationId: streetart
      parameters:
        - name: city
          in: query
          description: The city you want streetart for
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/StreetArtResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  StreetArtResponse:
    type: object
    properties:
      city: 
        type: string
      lat:
        type: string
      lon:
        type: string
      photos:
        type: array
        items:
           $ref: "#/definitions/Photo"
  Photo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      author:
        type: string
      text:
        type: string
      lat:
        type: string
      lon:
        type: string
      flickrUrl:
        type: string
      
    
  ErrorResponse:
    type: string
